### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by bethac07** [carpenter-singh-lab/2023_Cimini_NatureProtocols#13]
@ErinWeisbart Can you check the file locations in the README to see if they're still correct, I suspect they are not, and if so can you fix them?

We also want to make sure the following sentence ends up in there somewhere. TY!

`Cell Painting images and single-cell profiles are available at the Cell Painting Gallery on the Registry of Open Data on AWS (https://registry.opendata.aws/cellpainting-gallery/) under accession numbers cpg0000-jump-pilot and cpg0001-cellpainting-protocol.`

**Comment by ErinWeisbart** [comment]
Fixed with d1a987570811b0226bb2dd23a57c49ff9219a50b
