### ISSUE TITLE
utils.percent_score: below_threshold not multiplied with 100

### ISSUE THREAD

**Issue by danr** [carpenter-singh-lab/2023_Cimini_NatureProtocols#17]
Hi!

I noticed that below_threshold is not multiplied with 100 in percent_score here:
https://github.com/carpenter-singh-lab/2022_Cimini_NatureProtocols/blob/6b52a2775634dd2b496b137be21bf171c92672fb/notebooks/utils.py#L65

I believe this is correct the fix:
```diff
- return 100 * np.mean(above_threshold.astype(float)) + np.mean(below_threshold.astype(float)), perc_95, perc_5 
+ return 100 * np.mean(above_threshold.astype(float)) + 100 * np.mean(below_threshold.astype(float)), perc_95, perc_5 
```

Perhaps this will impact the plots in the paper.

**Comment by bethac07** [comment]
Oh my, yes, it sure looks like there was supposed to be parentheses there that certainly were not there!

I am going through and rerunning the affected notebooks now. My sincerest gratitude!
